name: api-platform-test-api

services:
  php:
    build:
      context: .
      target: dev
    image: api-platform-test-api-php:dev
    user: '${HOST_UID:-1000}:${HOST_GID:-1000}'
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app:app@database:5432/app?serverVersion=17&charset=utf8
    volumes:
      - ./:/app
    ports:
      - '127.0.0.1:${API_PORT:-8090}:8080'

  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'app', '-U', 'app']
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
